### PR TITLE
add webhook unit tests

### LINKED ISSUE #69: Refactor ManagementClientTests Architecture
### Motivation

* Currently, the tests are hard to maintain, read, and basically dependent on the live project in Kontent if new features are added and bugs are fixed.
* Re-generation requires there steps - Re-run ManagementClientTests with `private static readonly TestUtils.TestRunType _runType = TestUtils.TestRunType.MockFromFileSystem;`, after tests are green, commit changes in `~/Kentico.Kontent.Management.Tests/Data/*`

Come up with a better approach that would test the SDK functionality without necessity to pre-record requests and reposnse.

### Proposed solution

These are just possible enhancements:
* [x] Do now generate hash under `Data` folder - identify mock responses just by test name - so that update does not generate folder removal and addiction - and this pair is hard to distinguish
* [ ] Automate regeneration of the mock files
* [ ] Hardcode the JSONs and avoid auto-generation completely

### Additional context

* We might use [MAPI Swagger definition](https://kcdmaster.blob.core.windows.net/api-reference-specifications/management_api_v2.json) and use it for mock server -  (if URL does not work - reach out to @Simply007)

### Related issues

#79 #66 #64

### PR DESCRIPTION
**Pull request by gormal**
### Motivation

Fixes #69

Add unit tests for webhook methods 
### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Review by Simply007 — COMMENTED** [review]
Do we want to remove https://github.com/Kentico/kontent-management-sdk-net/blob/fix/69_webhook_tests/Kentico.Kontent.Management.Tests/ManagementClientTests/WebhookTests.cs as well as JSON responses from original tests?

**Review by Simply007 — COMMENTED** [review]
The tests seem fine - just one comment (above).

**Comment by gormal** [comment]
> Do we want to remove https://github.com/Kentico/kontent-management-sdk-net/blob/fix/69_webhook_tests/Kentico.Kontent.Management.Tests/ManagementClientTests/WebhookTests.cs as well as JSON responses from original tests?

We can remove them once all tests are re-written to unit tests.

**Comment by Simply007** [comment]
Let's remove old tests in separate pull request.

**Pull request merged**
